### ISSUE TITLE
Pre-train model cannot be downloaded

### ISSUE THREAD

**Issue by sandynctu** [uof1745-cmd/PCN#1]
Hi, thank you for your good works.
It seems the pre-train model download link is expired.
Can you update it?

Thanks!

**Comment by uof1745-cmd** [comment]
Hi, thank you for your appreciation.
We checked and found that the link is still availiable.
Maybe a network problem？

**Comment by sandynctu** [comment]
Hi, thank you for your reply.
Yes, it seems a network problem.
I can access it once I used VPN connected to China.
